<li><div class="preheader">
<ul class="hello-store">
<?php if($block->getPhoneNumber()) :?>
		<li><span class="phone-number"><?php echo $block->getPhoneNumber() ?></span></li>
<?php endif ?>
<?php if($block->isLoggedIn()) :  ?>
	<!-- <li><span class="customer-name"><?php echo __('Hello %1', $block->getCustomerData()->getFirstName() ) ?></span></li> -->
<?php else : ?>
	<!-- <li><span class="store-name"><?php echo $block->getStoreName() ?></span></li> -->
<?php endif ?>
<?php if($block->getHours()) :?>
	<li><span class="store-hours"><?php echo $block->getHours() ?></span></li>
<?php endif ?>
<!-- <?php if($block->isLoggedIn()) : ?>
	<li><span class="logout"><a href="<?php echo $this->getUrl('customer/account/logout') ?>"><?php echo __('Sign Out') ?></a></span></li>
<?php endif ?> -->
	<li><span class="contact"><a href="<?php echo $this->getUrl('contact') ?>"><?php echo __('Contact') ?></a></span></li>
	<li><?php echo $this->getChildHtml('top.flags'); ?></li>
</ul>
</div></li>
<?php
// echo $block->getStoreId() . '<br />';
// echo $block->getStoreCode() . '<br />';
// echo $block->getWebsiteId() . '<br />';
// echo $block->getStoreName() . '<br />';
// echo $block->getStoreUrl() . '<br />';
// echo $block->isStoreActive() . '<br />';
?>

