 <div class="about-us">
        <div class="featured-image responsive no-gradient-image">
            <div class="inner">
                <img src="<?= $this->getViewFileUrl("images/adult-apron-chef-1185552.jpg") ?>">
            </div>
        </div>
        <div class="bg-color white vertical-align">
            <div class="inner">
                <div class="content">
                <h2><?= __('Qui sommes nous ?') ?></h2>
                    <p>Pacha Distribution est votre grossiste en produit pour snack et restauration rapide dans les Bouches-du-Rhône mais aussi le Var et les Alpes de Haute Provence.<br>Basé à Marseille, nous assurons exclusivement la livraison de vos commandes pour des restaurants et particulièrement des snacks, boulangeries, pizzérias... Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
            </div>
        </div>
    </div>