<div class="contact-us">
        <div class="info bg-color green vertical-align">
            <div class="inner">
                <div class="content">
                    <h3>Nous sommes disponibles pour vous</h3>
                    <p class="icon icon-location">53 Bd Burel 13014 Marseille</p>
                    <p class="icon icon-phone">04 866 866 36  -  04 91 08 33 24</p>
                    <p class="icon icon-hours">Du lundi au vendredi<br>09:00 - 12:00 <br>13:00 - 18:00</p>
                </div>
            </div>
        </div>
        <div class="contact-form featured-image background-image" style="background-image: url(<?php echo $this->getViewFileUrl("images/adult-business-commerce-375889.jpg") ?>);">
            <div class="inner">
                <?= $this->getChildHtml('homeContactForm') ?>
            </div>
        </div>
    </div>