<div class="featured-image featured-main responsive">
		<div class="inner vertical-align">
			<div class="content ">
				<?php $cmsBlock = $this->getChildHtml('featured'); if($cmsBlock) : ?>
                <?php echo $cmsBlock  ?>
                <?php else : ?>
	            <h2>Faites vous livrer sans moderation cms</h2>
	            <a href="#" class="link link-button button">En savoir plus sur la livraison</a>
	            <img src="<?php echo $this->getViewFileUrl("images/adult-business-commerce-375889.jpg") ?>" />
	        	<?php endif ?>
			</div>
    	</div>
    </div>