<div class="featured-image featured-main responsive">
		<div class="inner vertical-align">
			<div class="content ">
	            <h2>Faites vous livrer 
	            sans moderation</h2>
	            <a href="#" class="link link-button button">En savoir plus sur la livraison</a>
	            <img src="<?php echo $this->getViewFileUrl("images/pacha/adult-business-commerce-375889.jpg") ?>" />
			</div>
    	</div>
    </div>