<?php $title = $block->getTitle() ? $block->getTitle() : __('Nos produits tendance New York') ?>
    <div class="featured-category featured-image main responsive">
        <div class="inner vertical-align">
            <div class="content">
                <?php $cmsBlock = $this->getChildHtml('featuredCategory'); if($cmsBlock) : ?>
                <?php echo $cmsBlock  ?>
                <?php else : ?>
                <h2 class="featured-title"><?= $title ?></h2>
                <a href="#" class="link link-button button">Voir tous nos produits</a>
                <img alt="NOS PRODUITS TENDANCE NEW YORK" src="<?php echo $this->getViewFileUrl("images/jakub-kapusnak-296880-unsplash.jpg") ?>">
                <?php endif ?>
            </div>
        </div>	
    </div>
    <div class="featured-product-list">
        <div class="inner">
            <?= $block->getChildHtml('featuredProductList') ?>
        </div>
    </div>
	<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $('.featured-product-list .product-items').slick({
                slidesToShow: 3,
                responsive: [
                {
                  breakpoint: 768,
                  settings: {
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    infinite: true,
                    dots: true
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 2,
                    slidesToScroll: 1,
                    dots: true
                  }
                }
              ]
            });
        });
    });
	</script>