<div class="grid-categories">
        <div class="bg-color green responsive">
            <div class="inner vertical-align">
                <div class="content">
                    <h3>Pomme de terre</h3>
                    <p>Retrouvez toutes nos conserves sur notre site disponible depuis notre menu</p>
                    <a href="#" class="link link-button button">Toutes nos conserves</a>
                </div>
            </div>
        </div>
        <div class="featured-image responsive">
            <div class="inner vertical-align">
                <div class="content">
                    <h3>Pains et tortillas</h3>
                    <p>Sublimez vos recettes avec les produits Pacha distribution</p>
                    <a href="#" class="link link-button button">Voir nos produits</a>
                    <img src="<?= $this->getViewFileUrl("images/emily-simenauer-639746-unsplash.jpg") ?>">
                </div>
            </div>
        </div>
         <div class="featured-image responsive">
            <div class="inner vertical-align">
                <div class="content">
                    <img src="<?= $this->getViewFileUrl("images/barbecue-bbq-chicken-106343.jpg") ?>">
                    <h3>Viandes halal</h3>
                    <p>Plutôt boeuf ou bien vollailes ? Grâce à notre gamme de viandes vous aurez du choix !</p>
                    <a href="#" class="link link-button button">Toutes nos conserves</a>
                </div>
            </div>
        </div>
        <div class="bg-color red responsive">
            <div class="inner vertical-align">
                <div class="content">
                    <h3>CONSOMMABLES</h3>
                    <p>Retrouvez tous nos produits surgelés sur notre site disponible depuis notre menu</p>
                    <a href="#" class="link link-button button">Toutes nos conserves</a>
                </div>
            </div>
        </div>
    </div>