<?php $title = $block->getTitle() ? $block->getTitle() : __("Une question ? Besoin d'aide ?") ?>
<div class="contact-us">
        <div class="bg-color red vertical-align">
            <div class="inner">
            	<div class="content">
        			<?php $cmsBlock = $this->getChildHtml('contactUs'); if($cmsBlock) : ?>
            		<?php echo $cmsBlock  ?>
            		<?php else : ?>
                	<h3><?= $title ?></h3>
                	<a href="contact" class="link link-button button"><?= __('Contact Us') ?> ?</a>
            		<?php endif ?>
            	</div>
            </div>
        </div>
    </div>