<?php $title = $block->getTitle() ? $block->getTitle() : __('Les promotions sont arrivées !') ?>
    <div class="featured-product widget-tabs-list">
        <div class="inner">
            <div class="featured-product-list">
                <div class="content">
                    <h2 class="featured-title"><?= $title ?></h2>
                    <div data-default-tab-title="<?= __('Categorie') ?>" class="widget-tabs"></div>
                    <?= $block->getChildHtml('featuredProductList') ?>
                </div>
            </div>
        </div>    
    </div>
	<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $('.featured-product-list .product-items').slick({
                slidesToShow: 4,
                responsive: [
                {
                  breakpoint: 980,
                  settings: {
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    infinite: true,
                    dots: true
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 2,
                    slidesToScroll: 1,
                    dots: true
                  }
                }
              ]
            });


            // Widgets tabs list

            widgetTabsListContainer = $('.widget-tabs-list .widget.block-products-list');

            if( $(widgetTabsListContainer).length>1 ) {

                var productItems =  widgetTabsListContainer.find('.product-items');

                productItems.not( productItems.first()).hide();


                $('.widget-tabs-list .widget.block-products-list').each(function(i){

                    var title= $(this).find('.block-title strong').text()!=="" ? $(this).find('.block-title strong').text() : 'Catégorie '+(i+1);

                    //const titleCapitalized = title.charAt(0).toUpperCase() + title.slice(1);

                    var html = '<button type="button" class="button cat-filter cat-filter-'+i+'" data-cat-filter="'+i+'"><span>'+title+'</span></button>';
                    
                    $('.widget-tabs-list .widget-tabs').append(html);

                });

                $('.cat-filter-0').addClass('active');
            
                $('.cat-filter').on('click', function(){
                    
                    $(this).addClass('active');
                    $('.cat-filter').not($(this)).removeClass('active');

                    list = $('.widget-tabs-list .widget.block-products-list .product-items');

                    list.hide();
                    
                    el = list.eq($(this).data('cat-filter'));
                    el.show();
                    el.slick('refresh');

                });
            }

        });
    });
	</script>