<div class="services">
	<div class="inner clearfix">
		<div class="col col-50">
			<div class="content services-slider">
				<img src="<?= $this->getViewFileUrl("images/appetizer-chicken-cuisine-1123250.jpg") ?>">
				<img src="<?= $this->getViewFileUrl("images/shutterstock_326380220.jpg") ?>">
				<img src="<?= $this->getViewFileUrl("images/shutterstock_572447653.jpg") ?>">
		</div>
		</div>
		<div class="col col-50 vertical-align">
			<div class="content">
				<h2>Des produits qui correspondent à vos besoins</h2>
				<p><b>Nous nous efforçons de répondre au mieux à votre besoin.</b><br>Pour qu’en une seule commande vous trouviez tous les produits nécessaires au bon fonctionnement de votre activité. 
				Des prix attractifs qui sauront vous satisfaire. 
				Une fidélité récompensée en fonction de la récurrence de vos achats</p>
				<a href="/services" class="services-link">Découvrez nos services</a>
			</div>
		</div>
	</div>
</div>
<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
        	//$('.services-slider').find('img').hide();
        	// $('.services-slider').find('img').wrap('<div class="item"></div>');
        	// $('.services-slider')
   //      	$('.services-slider').slick({
			//     slidesToShow: 1,
			//     slidesToScroll: 1,
			//     autoplay: false,
			//     autoplaySpeed: 2000,
			//     responsive: [
			//         {
			//             breakpoint: 9999,
			//             settings: "unslick"
			//         },
			//         {
			//             breakpoint: 767,
			//              settings: {
			//                     slidesToShow: 1,
			//                     slidesToScroll: 1,
			//                     infinite: false,
			//                     dots: false
			//                 }
			//         }
			//     ]
			// });


        });
    });
	</script>