
<a href="#" class="print_button_pdf action-download" data-file="catalog.pdf"><span><?= __('Télécharger la fiche produit') ?></span></a>

<script type="text/javascript">
    //<![CDATA[[
    // require(['jquery', 'jspdf' ], function ($, jsPDF) {
    //     $('.print_button_pdf').click(function (e){ 
    //         e.preventDefault();

    //         var pdf = new jsPDF('p', 'pt', 'a4');
    //         // source can be HTML-formatted string, or a reference
    //         // to an actual DOM element from which the text will be scraped.
    //         source = $('.gallery-placeholder')[0];
    //         // we support special element handlers. Register them with jQuery-style 
    //         // ID selector for either ID or node name. ("#iAmID", "div", "span" etc.)
    //         // There is no support for any other type of selectors 
    //         // (class, of compound) at this time.
    //         specialElementHandlers = {
    //             // element with id of "bypass" - jQuery style selector
    //             '#bypassme': function (element, renderer) {
    //                 // true = "handled elsewhere, bypass text extraction"
    //                 return true
    //             }
    //         };
    //         margins = {
    //             top: 200,
    //             bottom: 60,
    //             left: 40,
    //             width: 522
    //         };
            
    //         pdf.text('Titre',40,40);
    //         pdf.text('Sku',40,80);
    //         pdf.text('Prix et prix unit',40,120);

    //         // all coords and widths are in jsPDF instance's declared units
    //         // 'inches' in this case
            
    //         pdf.fromHTML(
    //             source, // HTML string or DOM elem ref.
    //             margins.left, // x coord
    //             margins.top, { // y coord
    //                 'width': margins.width, // max width of content on PDF
    //                 'elementHandlers': specialElementHandlers
    //             },

    //             function (dispose) {
    //                 // dispose: object with X, Y of the last line add to the PDF 
    //                 //          this allow the insertion of new lines after html
    //                 pdf.save('Product.pdf');
    //             }, margins);
    //         });

    //     });
    // ]]>
</script>