<?php $title = $block->getTitle() ? $block->getTitle() : __('Featured Product List') ?>
<div class="featured-category-list">
        <h2><?= $title ?></h2>
        <div class="inner">
            <?= $this->getChildHtml('featuredProductList') ?>
        </div>
    </div>
	<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $('.featured-category-list .product-items').slick({
                slidesToShow: 3,
                responsive: [
                {
                  breakpoint: 768,
                  settings: {
                    slidesToShow: 3,
                    slidesToScroll: 1,
                    infinite: true,
                    dots: true
                  }
                },
                {
                  breakpoint: 480,
                  settings: {
                    slidesToShow: 2,
                    slidesToScroll: 1,
                    dots: true
                  }
                }
              ]
            });
        });
    });
	</script>