<div class="process">
    <div class="how-it-works bg-color green">
            <h3 class="featured-title">Comment ça marche ?</h3>
        </div>
        <div class="inner">
        <div class="steps">
            <div class="step cart">
                <span class="ico-image">
                    <img src="<?php echo $this->getViewFileUrl("images/pacha/icon-cart@2x.png"); ?>">
                </span>
                <h4>SÉLECTIONNEZ VOS PRODUITS</h4>
                <p>Plus de 80 produits disponibles sur notre site. Toutes nos viandes sont certifiées Halal EHT et sont issues de bêtes abbatues selon le rite islamique.</p>
            </div>
            <div class="step order">
                <span class="ico-image">
                    <img src="<?php echo $this->getViewFileUrl("images/pacha/icon-order@2x.png"); ?>">
                </span>
                <h4>COMMANDE PRISE EN COMPTE</h4>
                <p>Du lundi au vendredi toute la journée nous vous livrons sous 24h ouvrés sur Marseille et ses alentours : livraison gratuites pour tout montant supérieur à 149€ HT.</p>
            </div>
            <div class="step shipping">
                <span class="ico-image">
                    <img src="<?php echo $this->getViewFileUrl("images/pacha/icon-shipping@2x.png"); ?>">
                </span>
                <h4>FAITES VOUS LIVRER</h4>
                <p>Tous vos produits sont préparés, nous livrons votre commande à l’adresse indiquée. Profitez en toute l’année !</p>
            </div>
        </div>
      </div>
    </div>
<script>
    // https://kenwheeler.github.io/slick/
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $('.steps').slick({
              dots: true,
              infinite: false,
              speed: 300,
              slidesToShow: 3,
              slidesToScroll: 3,
              dots: false,
              responsive: [
                {
                  breakpoint: 1024,
                  settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    infinite: true,
                    dots: false
                  }
                },
                {
                  breakpoint: 768,
                  settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    dots: true
                  }
                }
              ]
            });
        });
    });
</script>